stages:
  data-split:
    cmd: python src/data-prep.py
    deps:
    - classification/
    - src/data-prep.py
    outs:
    - data/test_data.npy
    - data/train_data.npy
    - data/val_data.npy
    - data/test_label.npy
    - data/train_label.npy
    - data/val_label.npy
  training:
    cmd: python src/train_model.py
    deps:
      - data/test_data.npy
      - data/train_data.npy
      - data/val_data.npy
      - data/test_label.npy
      - data/train_label.npy
      - data/val_label.npy
      - src/train_model.py
    params:
      - training.num_classes
      - training.nb_epoch
      - training.base_lr
    outs:
     
      - loss.png      
      - accuracy.png  
    metrics:
      - scores.json:
          cache: false


