name: Training

on: [push]

jobs:
  run:
    runs-on: [self-hosted,linux,x64,cml,gpu]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.12'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          echo "VIRTUAL ENV:" $VIRTUAL_ENV

          
          python3.8 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV

          pip install -r requirements.txt
          # Pull latest data from remote
          dvc pull
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro 
          
          git fetch --prune --unshallow
          # Add figure to the report
          echo "## Validating results by region"
          dvc plots show
            
          cml-publish auccuracy.png --md >> report.md
          cml-publish loss.png --md >> report.md
          
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md

